"""People almost everybody has seen a picture of, with the year they were born.

The birth year is not decoration here — it *is* the answer. Famous Faces asks who was born
first, so a wrong year makes a round that punishes the right answer. Everyone on this list
is somebody whose dates are not in dispute.

Spread matters as much as fame. A round needs four people born at least twenty-five years
apart, so the list is deliberately stretched across six centuries rather than crowded into
the twentieth, where most famous people inconveniently are.

Living people are included where they are so widely pictured that leaving them out would
make the list strange, but the balance leans historical: a photograph has to be old enough
to read as an era.

  (slug, name, what Commons files them under, birth year, one noun for what they are)
"""

PEOPLE = [
    # Before photography — painted and sculpted likenesses, which Commons holds plenty of
    ("leonardo-da-vinci", "Leonardo da Vinci", "Leonardo da Vinci portrait", 1452, "artist"),
    ("christopher-columbus", "Christopher Columbus", "Christopher Columbus portrait", 1451, "explorer"),
    ("michelangelo", "Michelangelo Buonarroti", "Michelangelo Buonarroti portrait", 1475, "artist"),
    ("william-shakespeare", "William Shakespeare", "William Shakespeare portrait", 1564, "writer"),
    ("galileo-galilei", "Galileo Galilei", "Galileo Galilei portrait", 1564, "scientist"),
    ("rembrandt", "Rembrandt", "Rembrandt self-portrait", 1606, "artist"),
    ("isaac-newton", "Isaac Newton", "Isaac Newton portrait", 1643, "scientist"),
    ("johann-sebastian-bach", "Johann Sebastian Bach", "Johann Sebastian Bach portrait", 1685, "composer"),
    ("benjamin-franklin", "Benjamin Franklin", "Benjamin Franklin portrait", 1706, "statesman"),
    ("george-washington", "George Washington", "George Washington portrait", 1732, "president"),
    ("wolfgang-amadeus-mozart", "Wolfgang Amadeus Mozart", "Wolfgang Amadeus Mozart portrait", 1756, "composer"),
    ("ludwig-van-beethoven", "Ludwig van Beethoven", "Ludwig van Beethoven portrait", 1770, "composer"),
    ("jane-austen", "Jane Austen", "Jane Austen portrait", 1775, "writer"),
    ("napoleon-bonaparte", "Napoleon Bonaparte", "Napoleon Bonaparte portrait", 1769, "emperor"),
    ("abraham-lincoln", "Abraham Lincoln", "Abraham Lincoln photograph", 1809, "president"),
    ("charles-darwin", "Charles Darwin", "Charles Darwin photograph", 1809, "scientist"),
    ("frederic-chopin", "Frédéric Chopin", "Frederic Chopin portrait", 1810, "composer"),
    ("charles-dickens", "Charles Dickens", "Charles Dickens photograph", 1812, "writer"),
    ("queen-victoria", "Queen Victoria", "Queen Victoria photograph", 1819, "queen"),
    ("florence-nightingale", "Florence Nightingale", "Florence Nightingale photograph", 1820, "nurse"),
    ("harriet-tubman", "Harriet Tubman", "Harriet Tubman photograph", 1822, "abolitionist"),
    ("leo-tolstoy", "Leo Tolstoy", "Leo Tolstoy photograph", 1828, "writer"),
    ("louisa-may-alcott", "Louisa May Alcott", "Louisa May Alcott photograph", 1832, "writer"),
    ("mark-twain", "Mark Twain", "Mark Twain photograph", 1835, "writer"),
    ("claude-monet", "Claude Monet", "Claude Monet photograph", 1840, "artist"),
    ("thomas-edison", "Thomas Edison", "Thomas Edison photograph", 1847, "inventor"),
    ("alexander-graham-bell", "Alexander Graham Bell", "Alexander Graham Bell photograph", 1847, "inventor"),
    ("vincent-van-gogh", "Vincent van Gogh", "Vincent van Gogh self-portrait", 1853, "artist"),
    ("nikola-tesla", "Nikola Tesla", "Nikola Tesla photograph", 1856, "inventor"),
    ("arthur-conan-doyle", "Arthur Conan Doyle", "Arthur Conan Doyle photograph", 1859, "writer"),
    ("marie-curie", "Marie Curie", "Marie Curie photograph", 1867, "scientist"),
    ("mahatma-gandhi", "Mahatma Gandhi", "Mahatma Gandhi photograph", 1869, "leader"),
    ("orville-wright", "Orville Wright", "Orville Wright photograph", 1871, "aviator"),
    ("winston-churchill", "Winston Churchill", "Winston Churchill photograph", 1874, "prime minister"),
    ("albert-einstein", "Albert Einstein", "Albert Einstein photograph", 1879, "scientist"),
    ("helen-keller", "Helen Keller", "Helen Keller photograph", 1880, "author"),
    ("pablo-picasso", "Pablo Picasso", "Pablo Picasso photograph", 1881, "artist"),
    ("franklin-d-roosevelt", "Franklin D. Roosevelt", "Franklin D. Roosevelt photograph", 1882, "president"),
    ("coco-chanel", "Coco Chanel", "Coco Chanel photograph", 1883, "designer"),
    ("eleanor-roosevelt", "Eleanor Roosevelt", "Eleanor Roosevelt photograph", 1884, "first lady"),
    ("charlie-chaplin", "Charlie Chaplin", "Charlie Chaplin photograph", 1889, "actor"),
    ("agatha-christie", "Agatha Christie", "Agatha Christie photograph", 1890, "writer"),
    ("amelia-earhart", "Amelia Earhart", "Amelia Earhart photograph", 1897, "aviator"),
    ("louis-armstrong", "Louis Armstrong", "Louis Armstrong photograph", 1901, "musician"),
    ("walt-disney", "Walt Disney", "Walt Disney photograph", 1901, "animator"),
    ("john-steinbeck", "John Steinbeck", "John Steinbeck photograph", 1902, "writer"),
    ("cary-grant", "Cary Grant", "Cary Grant photograph", 1904, "actor"),
    ("duke-ellington", "Duke Ellington", "Duke Ellington photograph", 1899, "musician"),
    ("katharine-hepburn", "Katharine Hepburn", "Katharine Hepburn photograph", 1907, "actress"),
    ("jacques-cousteau", "Jacques Cousteau", "Jacques Cousteau photograph", 1910, "explorer"),
    ("mother-teresa", "Mother Teresa", "Mother Teresa photograph", 1910, "nun"),
    ("rosa-parks", "Rosa Parks", "Rosa Parks photograph", 1913, "activist"),
    ("jesse-owens", "Jesse Owens", "Jesse Owens photograph", 1913, "athlete"),
    ("frank-sinatra", "Frank Sinatra", "Frank Sinatra photograph", 1915, "singer"),
    ("ella-fitzgerald", "Ella Fitzgerald", "Ella Fitzgerald photograph", 1917, "singer"),
    ("john-f-kennedy", "John F. Kennedy", "John F. Kennedy photograph", 1917, "president"),
    ("nelson-mandela", "Nelson Mandela", "Nelson Mandela photograph", 1918, "president"),
    ("jackie-robinson", "Jackie Robinson", "Jackie Robinson photograph", 1919, "athlete"),
    ("audrey-hepburn", "Audrey Hepburn", "Audrey Hepburn photograph", 1929, "actress"),
    ("queen-elizabeth-ii", "Queen Elizabeth II", "Queen Elizabeth II photograph", 1926, "queen"),
    ("marilyn-monroe", "Marilyn Monroe", "Marilyn Monroe photograph", 1926, "actress"),
    ("martin-luther-king", "Martin Luther King Jr.", "Martin Luther King Jr photograph", 1929, "leader"),
    ("neil-armstrong", "Neil Armstrong", "Neil Armstrong photograph", 1930, "astronaut"),
    ("johnny-cash", "Johnny Cash", "Johnny Cash photograph", 1932, "singer"),
    ("elvis-presley", "Elvis Presley", "Elvis Presley photograph", 1935, "singer"),
    ("muhammad-ali", "Muhammad Ali", "Muhammad Ali photograph", 1942, "boxer"),
    ("paul-mccartney", "Paul McCartney", "Paul McCartney photograph", 1942, "musician"),
    ("dolly-parton", "Dolly Parton", "Dolly Parton photograph", 1946, "singer"),
    ("stephen-hawking", "Stephen Hawking", "Stephen Hawking photograph", 1942, "scientist"),
    ("pele", "Pelé", "Pele footballer photograph", 1940, "footballer"),
    ("billie-jean-king", "Billie Jean King", "Billie Jean King photograph", 1943, "tennis player"),
    ("bob-marley", "Bob Marley", "Bob Marley photograph", 1945, "singer"),
    ("freddie-mercury", "Freddie Mercury", "Freddie Mercury photograph", 1946, "singer"),
    ("wayne-gretzky", "Wayne Gretzky", "Wayne Gretzky photograph", 1961, "hockey player"),
    ("michael-jackson", "Michael Jackson", "Michael Jackson photograph", 1958, "singer"),
    ("michael-jordan", "Michael Jordan", "Michael Jordan photograph", 1963, "basketball player"),
    ("serena-williams", "Serena Williams", "Serena Williams photograph", 1981, "tennis player"),
    ("roger-federer", "Roger Federer", "Roger Federer photograph", 1981, "tennis player"),
    ("usain-bolt", "Usain Bolt", "Usain Bolt photograph", 1986, "sprinter"),
    ("lionel-messi", "Lionel Messi", "Lionel Messi photograph", 1987, "footballer"),
    ("katy-perry", "Katy Perry", "Katy Perry photograph", 1984, "singer"),
    ("taylor-swift", "Taylor Swift", "Taylor Swift photograph", 1989, "singer"),
    ("socrates", "Socrates", "Socrates portrait", -470, "philosopher"),
    ("cleopatra", "Cleopatra", "Cleopatra portrait", -69, "queen"),
    ("julius-caesar", "Julius Caesar", "Julius Caesar portrait", -100, "general"),
    ("confucius", "Confucius", "Confucius portrait", -551, "philosopher"),
    ("joan-of-arc", "Joan of Arc", "Joan of Arc portrait", 1412, "soldier"),
    ("marco-polo", "Marco Polo", "Marco Polo portrait", 1254, "explorer"),
    ("copernicus", "Nicolaus Copernicus", "Nicolaus Copernicus portrait", 1473, "astronomer"),
    ("martin-luther", "Martin Luther", "Martin Luther portrait", 1483, "reformer"),
    ("elizabeth-i", "Elizabeth I", "Elizabeth I portrait", 1533, "queen"),
    ("cervantes", "Miguel de Cervantes", "Miguel de Cervantes portrait", 1547, "writer"),
    ("johannes-kepler", "Johannes Kepler", "Johannes Kepler portrait", 1571, "astronomer"),
    ("vermeer", "Johannes Vermeer", "Johannes Vermeer portrait", 1632, "artist"),
    ("bach-cpe", "Antonio Vivaldi", "Antonio Vivaldi portrait", 1678, "composer"),
    ("voltaire", "Voltaire", "Voltaire portrait", 1694, "writer"),
    ("captain-cook", "James Cook", "James Cook portrait", 1728, "explorer"),
    ("mary-wollstonecraft", "Mary Wollstonecraft", "Mary Wollstonecraft portrait", 1759, "writer"),
    ("william-blake", "William Blake", "William Blake portrait", 1757, "poet"),
    ("john-adams", "John Adams", "John Adams portrait", 1735, "president"),
    ("thomas-jefferson", "Thomas Jefferson", "Thomas Jefferson portrait", 1743, "president"),
    ("goya", "Francisco Goya", "Francisco Goya portrait", 1746, "artist"),
    ("robert-burns", "Robert Burns", "Robert Burns portrait", 1759, "poet"),
    ("beethoven-2", "Franz Schubert", "Franz Schubert portrait", 1797, "composer"),
    ("simon-bolivar", "Simón Bolívar", "Simón Bolívar portrait", 1783, "liberator"),
    ("mary-shelley", "Mary Shelley", "Mary Shelley portrait", 1797, "writer"),
    ("honore-de-balzac", "Honoré de Balzac", "Honoré de Balzac portrait", 1799, "writer"),
    ("john-stuart-mill", "John Stuart Mill", "John Stuart Mill portrait", 1806, "philosopher"),
    ("edgar-allan-poe", "Edgar Allan Poe", "Edgar Allan Poe portrait", 1809, "writer"),
    ("felix-mendelssohn", "Felix Mendelssohn", "Felix Mendelssohn portrait", 1809, "composer"),
    ("giuseppe-verdi", "Giuseppe Verdi", "Giuseppe Verdi portrait", 1813, "composer"),
    ("charlotte-bronte", "Charlotte Brontë", "Charlotte Brontë portrait", 1816, "writer"),
    ("karl-marx", "Karl Marx", "Karl Marx portrait", 1818, "philosopher"),
    ("emily-bronte", "Emily Brontë", "Emily Brontë portrait", 1818, "writer"),
    ("walt-whitman", "Walt Whitman", "Walt Whitman portrait", 1819, "poet"),
    ("gregor-mendel", "Gregor Mendel", "Gregor Mendel portrait", 1822, "scientist"),
    ("louis-pasteur", "Louis Pasteur", "Louis Pasteur portrait", 1822, "scientist"),
    ("jules-verne", "Jules Verne", "Jules Verne portrait", 1828, "writer"),
    ("emily-dickinson", "Emily Dickinson", "Emily Dickinson portrait", 1830, "poet"),
    ("lewis-carroll", "Lewis Carroll", "Lewis Carroll portrait", 1832, "writer"),
    ("edgar-degas", "Edgar Degas", "Edgar Degas portrait", 1834, "artist"),
    ("pierre-auguste-renoir", "Pierre-Auguste Renoir", "Pierre-Auguste Renoir portrait", 1841, "artist"),
    ("antonio-gaudi", "Antoni Gaudí", "Antoni Gaudí portrait", 1852, "architect"),
    ("oscar-wilde", "Oscar Wilde", "Oscar Wilde portrait", 1854, "writer"),
    ("sigmund-freud", "Sigmund Freud", "Sigmund Freud portrait", 1856, "psychoanalyst"),
    ("joseph-conrad", "Joseph Conrad", "Joseph Conrad portrait", 1857, "writer"),
    ("max-planck", "Max Planck", "Max Planck portrait", 1858, "physicist"),
    ("gustav-klimt", "Gustav Klimt", "Gustav Klimt portrait", 1862, "artist"),
    ("henry-ford", "Henry Ford", "Henry Ford portrait", 1863, "industrialist"),
    ("wassily-kandinsky", "Wassily Kandinsky", "Wassily Kandinsky portrait", 1866, "artist"),
    ("frank-lloyd-wright", "Frank Lloyd Wright", "Frank Lloyd Wright portrait", 1867, "architect"),
    ("henri-matisse", "Henri Matisse", "Henri Matisse portrait", 1869, "artist"),
    ("rosa-luxemburg", "Rosa Luxemburg", "Rosa Luxemburg portrait", 1871, "activist"),
    ("bertrand-russell", "Bertrand Russell", "Bertrand Russell portrait", 1872, "philosopher"),
    ("harry-houdini", "Harry Houdini", "Harry Houdini portrait", 1874, "magician"),
    ("carl-jung", "Carl Jung", "Carl Jung portrait", 1875, "psychiatrist"),
    ("jack-london", "Jack London", "Jack London portrait", 1876, "writer"),
    ("virginia-woolf", "Virginia Woolf", "Virginia Woolf portrait", 1882, "writer"),
    ("franz-kafka", "Franz Kafka", "Franz Kafka portrait", 1883, "writer"),
    ("niels-bohr", "Niels Bohr", "Niels Bohr portrait", 1885, "physicist"),
    ("georgia-okeeffe", "Georgia O'Keeffe", "Georgia O'Keeffe portrait", 1887, "artist"),
    ("erwin-schrodinger", "Erwin Schrödinger", "Erwin Schrödinger portrait", 1887, "physicist"),
    ("tj-eliot", "T. S. Eliot", "T. S. Eliot portrait", 1888, "poet"),
    ("alfred-hitchcock", "Alfred Hitchcock", "Alfred Hitchcock portrait", 1899, "director"),
    ("ernest-hemingway", "Ernest Hemingway", "Ernest Hemingway portrait", 1899, "writer"),
    ("louis-armstrong-2", "Duke Kahanamoku", "Duke Kahanamoku portrait", 1890, "swimmer"),
    ("jrr-tolkien", "J. R. R. Tolkien", "J. R. R. Tolkien portrait", 1892, "writer"),
    ("mao-zedong", "Mao Zedong", "Mao Zedong portrait", 1893, "leader"),
    ("aldous-huxley", "Aldous Huxley", "Aldous Huxley portrait", 1894, "writer"),
    ("f-scott-fitzgerald", "F. Scott Fitzgerald", "F. Scott Fitzgerald portrait", 1896, "writer"),
    ("jorge-luis-borges", "Jorge Luis Borges", "Jorge Luis Borges portrait", 1899, "writer"),
    ("louis-armstrong-3", "Enrico Fermi", "Enrico Fermi portrait", 1901, "physicist"),
    ("john-steinbeck-2", "George Orwell", "George Orwell portrait", 1903, "writer"),
    ("frida-kahlo", "Frida Kahlo", "Frida Kahlo portrait", 1907, "artist"),
    ("jacques-tati", "Jacques Tati", "Jacques Tati portrait", 1907, "director"),
    ("simone-de-beauvoir", "Simone de Beauvoir", "Simone de Beauvoir portrait", 1908, "writer"),
    ("alan-turing", "Alan Turing", "Alan Turing portrait", 1912, "scientist"),
    ("julia-child", "Julia Child", "Julia Child portrait", 1912, "chef"),
    ("albert-camus", "Albert Camus", "Albert Camus portrait", 1913, "writer"),
    ("orson-welles", "Orson Welles", "Orson Welles portrait", 1915, "director"),
    ("billie-holiday", "Billie Holiday", "Billie Holiday portrait", 1915, "singer"),
    ("roald-dahl", "Roald Dahl", "Roald Dahl portrait", 1916, "writer"),
    ("ella-fitzgerald-2", "Ingrid Bergman", "Ingrid Bergman portrait", 1915, "actress"),
    ("leonard-bernstein", "Leonard Bernstein", "Leonard Bernstein portrait", 1918, "composer"),
    ("doris-day", "Doris Day", "Doris Day portrait", 1922, "actress"),
    ("charlie-parker", "Charlie Parker", "Charlie Parker portrait", 1920, "musician"),
    ("maria-callas", "Maria Callas", "Maria Callas portrait", 1923, "singer"),
    ("james-baldwin", "James Baldwin", "James Baldwin portrait", 1924, "writer"),
    ("miles-davis", "Miles Davis", "Miles Davis portrait", 1926, "musician"),
    ("chuck-berry", "Chuck Berry", "Chuck Berry portrait", 1926, "musician"),
    ("gabriel-garcia-marquez", "Gabriel García Márquez", "Gabriel García Márquez portrait", 1927, "writer"),
    ("andy-warhol", "Andy Warhol", "Andy Warhol portrait", 1928, "artist"),
    ("maya-angelou", "Maya Angelou", "Maya Angelou portrait", 1928, "poet"),
    ("anne-frank", "Anne Frank", "Anne Frank portrait", 1929, "diarist"),
    ("grace-kelly", "Grace Kelly", "Grace Kelly portrait", 1929, "actress"),
    ("sean-connery", "Sean Connery", "Sean Connery portrait", 1930, "actor"),
    ("ray-charles", "Ray Charles", "Ray Charles portrait", 1930, "musician"),
    ("toni-morrison", "Toni Morrison", "Toni Morrison portrait", 1931, "writer"),
    ("elizabeth-taylor", "Elizabeth Taylor", "Elizabeth Taylor portrait", 1932, "actress"),
    ("yuri-gagarin", "Yuri Gagarin", "Yuri Gagarin portrait", 1934, "cosmonaut"),
    ("brigitte-bardot", "Brigitte Bardot", "Brigitte Bardot portrait", 1934, "actress"),
    ("luciano-pavarotti", "Luciano Pavarotti", "Luciano Pavarotti portrait", 1935, "singer"),
    ("aretha-franklin", "Aretha Franklin", "Aretha Franklin portrait", 1942, "singer"),
    ("jimi-hendrix", "Jimi Hendrix", "Jimi Hendrix portrait", 1942, "musician"),
    ("harrison-ford", "Harrison Ford", "Harrison Ford portrait", 1942, "actor"),
    ("mick-jagger", "Mick Jagger", "Mick Jagger portrait", 1943, "musician"),
    ("bob-dylan", "Bob Dylan", "Bob Dylan portrait", 1941, "musician"),
    ("john-lennon", "John Lennon", "John Lennon portrait", 1940, "musician"),
    ("bruce-lee", "Bruce Lee", "Bruce Lee portrait", 1940, "actor"),
    ("david-bowie", "David Bowie", "David Bowie portrait", 1947, "musician"),
    ("stephen-king", "Stephen King", "Stephen King portrait", 1947, "writer"),
    ("freddie-mercury-2", "Elton John", "Elton John portrait", 1947, "musician"),
    ("meryl-streep", "Meryl Streep", "Meryl Streep portrait", 1949, "actress"),
    ("stevie-wonder", "Stevie Wonder", "Stevie Wonder portrait", 1950, "musician"),
    ("bill-gates", "Bill Gates", "Bill Gates portrait", 1955, "businessman"),
    ("steve-jobs", "Steve Jobs", "Steve Jobs portrait", 1955, "businessman"),
    ("whitney-houston", "Whitney Houston", "Whitney Houston portrait", 1963, "singer"),
    ("madonna", "Madonna", "Madonna portrait", 1958, "singer"),
    ("oprah-winfrey", "Oprah Winfrey", "Oprah Winfrey portrait", 1954, "broadcaster"),
    ("prince", "Prince", "Prince portrait", 1958, "musician"),
    ("diana-princess-of-wales", "Diana, Princess of Wales", "Diana, Princess of Wales portrait", 1961, "princess"),
    ("barack-obama", "Barack Obama", "Barack Obama portrait", 1961, "president"),
    ("tom-hanks", "Tom Hanks", "Tom Hanks portrait", 1956, "actor"),
]
