"""Named landmarks to add, one per line: the title shown, and its Wikipedia article.

Chosen the way the rest of the pack was: places a person would recognise from a single
photograph, spread across the world, with a Wikipedia lead image to pin them to.
Coordinates, the place name and the fact are fetched — only the choosing is done here.
"""

LANDMARKS = [
    # --- British Isles
    ("Buckingham Palace", "Buckingham Palace"),
    ("The Houses of Parliament", "Palace of Westminster"),
    ("St Paul's Cathedral", "St Paul's Cathedral"),
    ("The London Eye", "London Eye"),
    ("Windsor Castle", "Windsor Castle"),
    ("Hadrian's Wall", "Hadrian's Wall"),
    ("York Minster", "York Minster"),
    ("Durham Cathedral", "Durham Cathedral"),
    ("Canterbury Cathedral", "Canterbury Cathedral"),
    ("Bath's Roman Baths", "Roman Baths (Bath)"),
    ("The Royal Crescent", "Royal Crescent"),
    ("Blenheim Palace", "Blenheim Palace"),
    ("The Forth Bridge", "Forth Bridge"),
    ("Eilean Donan Castle", "Eilean Donan"),
    ("Glenfinnan Viaduct", "Glenfinnan Viaduct"),
    ("Loch Ness", "Loch Ness"),
    ("Ben Nevis", "Ben Nevis"),
    ("The Isle of Skye", "Isle of Skye"),
    ("Conwy Castle", "Conwy Castle"),
    ("Snowdon", "Snowdon"),
    ("Caernarfon Castle", "Caernarfon Castle"),
    ("The Rock of Cashel", "Rock of Cashel"),
    ("Blarney Castle", "Blarney Castle"),
    ("Trinity College Dublin", "Trinity College Dublin"),
    ("Kilmainham Gaol", "Kilmainham Gaol"),
    ("The Ring of Kerry", "Ring of Kerry"),
    ("Dunluce Castle", "Dunluce Castle"),
    ("Portmeirion", "Portmeirion"),
    ("Tintern Abbey", "Tintern Abbey"),
    ("The Angel of the North", "Angel of the North"),

    # --- France, Belgium, the Netherlands
    ("The Louvre", "Louvre"),
    ("The Palace of Versailles", "Palace of Versailles"),
    ("Mont Blanc", "Mont Blanc"),
    ("The Pont du Gard", "Pont du Gard"),
    ("Chambord", "Château de Chambord"),
    ("Chenonceau", "Château de Chenonceau"),
    ("Carcassonne", "Cité de Carcassonne"),
    ("The Palais Garnier", "Palais Garnier"),
    ("Sacré-Cœur", "Sacré-Cœur, Paris"),
    ("The Millau Viaduct", "Millau Viaduct"),
    ("Chartres Cathedral", "Chartres Cathedral"),
    ("The Grand Place", "Grand-Place"),
    ("The Atomium", "Atomium"),
    ("Bruges", "Bruges"),
    ("The Rijksmuseum", "Rijksmuseum"),
    ("Kinderdijk's windmills", "Kinderdijk"),
    ("The Keukenhof", "Keukenhof"),
    ("Anne Frank House", "Anne Frank House"),

    # --- Iberia, Italy, Greece
    ("The Alcázar of Segovia", "Alcázar of Segovia"),
    ("The Aqueduct of Segovia", "Aqueduct of Segovia"),
    ("The Guggenheim Bilbao", "Guggenheim Museum Bilbao"),
    ("Park Güell", "Park Güell"),
    ("The Mezquita of Córdoba", "Mosque–Cathedral of Córdoba"),
    ("Santiago de Compostela Cathedral", "Santiago de Compostela Cathedral"),
    ("Belém Tower", "Belém Tower"),
    ("Pena Palace", "Pena Palace"),
    ("The Douro Valley", "Douro"),
    ("Saint Mark's Basilica", "St Mark's Basilica"),
    ("The Rialto Bridge", "Rialto Bridge"),
    ("The Duomo of Florence", "Florence Cathedral"),
    ("The Ponte Vecchio", "Ponte Vecchio"),
    ("The Pantheon", "Pantheon, Rome"),
    ("The Spanish Steps", "Spanish Steps"),
    ("Pompeii", "Pompeii"),
    ("Mount Vesuvius", "Mount Vesuvius"),
    ("The Amalfi Coast", "Amalfi Coast"),
    ("Cinque Terre", "Cinque Terre"),
    ("Lake Como", "Lake Como"),
    ("The Milan Cathedral", "Milan Cathedral"),
    ("Mount Etna", "Mount Etna"),
    ("The Valley of the Temples", "Valley of the Temples"),
    ("Meteora", "Meteora"),
    ("Santorini", "Santorini"),
    ("The Temple of Poseidon", "Cape Sounion"),
    ("Delphi", "Delphi"),
    ("Knossos", "Knossos"),

    # --- Central and northern Europe
    ("Prague Castle", "Prague Castle"),
    ("The Charles Bridge", "Charles Bridge"),
    ("The Cologne Cathedral", "Cologne Cathedral"),
    ("The Berlin Wall", "Berlin Wall"),
    ("The Reichstag", "Reichstag building"),
    ("Heidelberg Castle", "Heidelberg Castle"),
    ("The Zugspitze", "Zugspitze"),
    ("Schönbrunn Palace", "Schönbrunn Palace"),
    ("Hallstatt", "Hallstatt"),
    ("The Chapel Bridge", "Chapel Bridge"),
    ("The Jungfrau", "Jungfrau"),
    ("Château de Chillon", "Chillon Castle"),
    ("The Parliament of Budapest", "Hungarian Parliament Building"),
    ("Wawel Castle", "Wawel Castle"),
    ("Kraków's Main Square", "Main Square, Kraków"),
    ("The Little Mermaid", "The Little Mermaid (statue)"),
    ("Nyhavn", "Nyhavn"),
    ("Kronborg Castle", "Kronborg"),
    ("The Øresund Bridge", "Øresund Bridge"),
    ("Gamla Stan", "Gamla stan"),
    ("The Geirangerfjord", "Geirangerfjord"),
    ("Bryggen", "Bryggen"),
    ("Preikestolen", "Preikestolen"),
    ("The Blue Lagoon", "Blue Lagoon (geothermal spa)"),
    ("Gullfoss", "Gullfoss"),
    ("Hallgrímskirkja", "Hallgrímskirkja"),
    ("The Suomenlinna fortress", "Suomenlinna"),
    ("Saint Isaac's Cathedral", "Saint Isaac's Cathedral"),
    ("The Hermitage", "Hermitage Museum"),
    ("The Church of the Savior on Spilled Blood", "Church of the Savior on Blood"),

    # --- Africa and the Middle East
    ("The Sphinx", "Great Sphinx of Giza"),
    ("Abu Simbel", "Abu Simbel"),
    ("The Karnak Temple", "Karnak"),
    ("The Valley of the Kings", "Valley of the Kings"),
    ("The Suez Canal", "Suez Canal"),
    ("The Hassan II Mosque", "Hassan II Mosque"),
    ("Marrakesh's Jemaa el-Fnaa", "Jemaa el-Fnaa"),
    ("Chefchaouen", "Chefchaouen"),
    ("The Sahara", "Sahara"),
    ("Lalibela", "Lalibela"),
    ("The Serengeti", "Serengeti"),
    ("The Ngorongoro Crater", "Ngorongoro Conservation Area"),
    ("The Okavango Delta", "Okavango Delta"),
    ("The Cape of Good Hope", "Cape of Good Hope"),
    ("Robben Island", "Robben Island"),
    ("The Blyde River Canyon", "Blyde River Canyon"),
    ("The Great Mosque of Djenné", "Great Mosque of Djenné"),
    ("The Dome of the Rock", "Dome of the Rock"),
    ("The Western Wall", "Western Wall"),
    ("The Church of the Holy Sepulchre", "Church of the Holy Sepulchre"),
    ("The Dead Sea", "Dead Sea"),
    ("The Burj Khalifa", "Burj Khalifa"),
    ("The Burj Al Arab", "Burj Al Arab"),
    ("The Sheikh Zayed Mosque", "Sheikh Zayed Mosque"),
    ("The Blue Mosque", "Blue Mosque, Istanbul"),
    ("The Topkapi Palace", "Topkapı Palace"),
    ("Pamukkale", "Pamukkale"),
    ("Cappadocia", "Cappadocia"),
    ("Persepolis", "Persepolis"),
    ("The Nasir al-Mulk Mosque", "Nasir-ol-Molk Mosque"),

    # --- South and East Asia
    ("The Gateway of India", "Gateway of India"),
    ("The Amber Fort", "Amer Fort"),
    ("The Hawa Mahal", "Hawa Mahal"),
    ("The Red Fort", "Red Fort"),
    ("Varanasi's ghats", "Ghats in Varanasi"),
    ("The Lotus Temple", "Lotus Temple"),
    ("Mount Everest", "Mount Everest"),
    ("The Boudhanath Stupa", "Boudhanath"),
    ("Sigiriya", "Sigiriya"),
    ("The Temple of the Tooth", "Sri Dalada Maligawa"),
    ("Borobudur", "Borobudur"),
    ("Mount Bromo", "Mount Bromo"),
    ("Halong Bay", "Hạ Long Bay"),
    ("The Grand Palace", "Grand Palace"),
    ("Wat Arun", "Wat Arun"),
    ("Ayutthaya", "Ayutthaya Historical Park"),
    ("The Petronas Towers", "Petronas Towers"),
    ("The Marina Bay Sands", "Marina Bay Sands"),
    ("The Gardens by the Bay", "Gardens by the Bay"),
    ("The Terracotta Army", "Terracotta Army"),
    ("The Temple of Heaven", "Temple of Heaven"),
    ("The Li River", "Li River"),
    ("The Bund", "The Bund"),
    ("Victoria Harbour", "Victoria Harbour"),
    ("The Tokyo Tower", "Tokyo Tower"),
    ("The Fushimi Inari Shrine", "Fushimi Inari-taisha"),
    ("Himeji Castle", "Himeji Castle"),
    ("The Itsukushima Shrine", "Itsukushima Shrine"),
    ("The Hiroshima Peace Memorial", "Hiroshima Peace Memorial"),
    ("Shibuya Crossing", "Shibuya Crossing"),
    ("Gyeongbokgung", "Gyeongbokgung"),
    ("The Bulguksa Temple", "Bulguksa"),

    # --- Oceania
    ("The Twelve Apostles", "The Twelve Apostles (Victoria)"),
    ("The Great Barrier Reef", "Great Barrier Reef"),
    ("Bondi Beach", "Bondi Beach"),
    ("The Blue Mountains", "Blue Mountains (New South Wales)"),
    ("Kata Tjuta", "Kata Tjuta"),
    ("The Pinnacles", "Pinnacles Desert"),
    ("Mount Cook", "Aoraki / Mount Cook"),
    ("The Sky Tower", "Sky Tower (Auckland)"),
    ("Rotorua's geysers", "Whakarewarewa"),
    ("Franz Josef Glacier", "Franz Josef Glacier"),
    ("Lake Tekapo", "Lake Tekapo"),
    ("Bora Bora", "Bora Bora"),

    # --- North America
    ("The Brooklyn Bridge", "Brooklyn Bridge"),
    ("Central Park", "Central Park"),
    ("The Chrysler Building", "Chrysler Building"),
    ("The Flatiron Building", "Flatiron Building"),
    ("The Lincoln Memorial", "Lincoln Memorial"),
    ("The Washington Monument", "Washington Monument"),
    ("The United States Capitol", "United States Capitol"),
    ("The Jefferson Memorial", "Jefferson Memorial"),
    ("Independence Hall", "Independence Hall"),
    ("The Liberty Bell", "Liberty Bell"),
    ("Fenway Park", "Fenway Park"),
    ("The Golden Dome of Notre Dame", "Main Building (University of Notre Dame)"),
    ("Willis Tower", "Willis Tower"),
    ("The Cloud Gate", "Cloud Gate"),
    ("Mount Vernon", "Mount Vernon"),
    ("Monticello", "Monticello"),
    ("The Biltmore Estate", "Biltmore Estate"),
    ("The Blue Ridge Parkway", "Blue Ridge Parkway"),
    ("Cape Hatteras Lighthouse", "Cape Hatteras Light"),
    ("The Everglades", "Everglades"),
    ("Key West", "Key West"),
    ("The French Quarter", "French Quarter"),
    ("The Alamo", "Alamo Mission in San Antonio"),
    ("The San Antonio River Walk", "San Antonio River Walk"),
    ("Carlsbad Caverns", "Carlsbad Caverns National Park"),
    ("White Sands", "White Sands National Park"),
    ("Taos Pueblo", "Taos Pueblo"),
    ("The Painted Desert", "Painted Desert (Arizona)"),
    ("Horseshoe Bend", "Horseshoe Bend (Arizona)"),
    ("Antelope Canyon", "Antelope Canyon"),
    ("Bryce Canyon", "Bryce Canyon National Park"),
    ("Zion Canyon", "Zion National Park"),
    ("Arches National Park", "Arches National Park"),
    ("Devils Tower", "Devils Tower"),
    ("The Grand Prismatic Spring", "Grand Prismatic Spring"),
    ("Glacier National Park", "Glacier National Park (U.S.)"),
    ("Mount Rainier", "Mount Rainier"),
    ("Crater Lake Lodge", "Crater Lake Lodge"),
    ("Multnomah Falls", "Multnomah Falls"),
    ("The Hollywood Sign", "Hollywood Sign"),
    ("The Santa Monica Pier", "Santa Monica Pier"),
    ("The Hearst Castle", "Hearst Castle"),
    ("Lake Tahoe", "Lake Tahoe"),
    ("The Redwoods", "Redwood National and State Parks"),
    ("Death Valley", "Death Valley"),
    ("Denali", "Denali"),
    ("The Mendenhall Glacier", "Mendenhall Glacier"),
    ("Waikiki Beach", "Waikiki"),
    ("Diamond Head", "Diamond Head, Hawaii"),
    ("The Kilauea volcano", "Kīlauea"),
    ("The Banff Springs Hotel", "Banff Springs Hotel"),
    ("Moraine Lake", "Moraine Lake"),
    ("The CN Tower", "CN Tower"),
    ("Parliament Hill", "Parliament Hill"),
    ("Peggy's Cove", "Peggys Cove, Nova Scotia"),
    ("Old Quebec", "Old Quebec"),
    ("The Bay of Fundy", "Bay of Fundy"),
    ("Teotihuacan", "Teotihuacan"),
    ("Tulum", "Tulum"),
    ("The Palacio de Bellas Artes", "Palacio de Bellas Artes"),
    ("Guanajuato", "Guanajuato"),

    # --- Central and South America
    ("The Panama Canal", "Panama Canal"),
    ("Arenal Volcano", "Arenal Volcano"),
    ("Tikal", "Tikal"),
    ("Lake Atitlán", "Lake Atitlán"),
    ("The Galápagos Islands", "Galápagos Islands"),
    ("The Nazca Lines", "Nazca Lines"),
    ("Rainbow Mountain", "Vinicunca"),
    ("Lake Titicaca", "Lake Titicaca"),
    ("The Salar de Uyuni", "Salar de Uyuni"),
    ("The Atacama Desert", "Atacama Desert"),
    ("Torres del Paine", "Torres del Paine National Park"),
    ("Perito Moreno Glacier", "Perito Moreno Glacier"),
    ("The Copacabana", "Copacabana, Rio de Janeiro"),
    ("Sugarloaf Mountain", "Sugarloaf Mountain"),
    ("The Amazon River", "Amazon River"),
    ("Cartagena's walled city", "Walled City of Cartagena"),
    ("The Angel Falls", "Angel Falls"),
]

# --- Second batch: more of the same test — would somebody know it from one photograph?
LANDMARKS += [
    ("The Shard", "The Shard"),
    ("The Clifton Suspension Bridge", "Clifton Suspension Bridge"),
    ("Salisbury Cathedral", "Salisbury Cathedral"),
    ("The Giant's Ring", "Giant's Ring"),
    ("Bodiam Castle", "Bodiam Castle"),
    ("The Seven Sisters", "Seven Sisters, Sussex"),
    ("St Michael's Mount", "St Michael's Mount"),
    ("The Lake District", "Lake District"),
    ("Stirling Castle", "Stirling Castle"),
    ("The Kelpies", "The Kelpies"),
    ("Giant's Causeway's Carrick-a-Rede", "Carrick-a-Rede Rope Bridge"),
    ("Newgrange", "Newgrange"),
    ("The Cliffs of Étretat", "Étretat"),
    ("The Normandy landing beaches", "Normandy landings"),
    ("Rouen Cathedral", "Rouen Cathedral"),
    ("The Pont Neuf", "Pont Neuf"),
    ("The Arles amphitheatre", "Arles Amphitheatre"),
    ("Avignon's Palais des Papes", "Palais des Papes"),
    ("The Verdon Gorge", "Verdon Gorge"),
    ("Lake Bled", "Lake Bled"),
    ("Plitvice Lakes", "Plitvice Lakes National Park"),
    ("Dubrovnik's walls", "Walls of Dubrovnik"),
    ("Diocletian's Palace", "Diocletian's Palace"),
    ("The Blue Grotto", "Blue Grotto (Capri)"),
    ("The Bridge of Sighs", "Bridge of Sighs"),
    ("San Gimignano", "San Gimignano"),
    ("Siena's Piazza del Campo", "Piazza del Campo"),
    ("Positano", "Positano"),
    ("Matera", "Matera"),
    ("The Trulli of Alberobello", "Trulli of Alberobello"),
    ("Lake Garda", "Lake Garda"),
    ("The Dolomites", "Dolomites"),
    ("The Bernina Express", "Bernina railway"),
    ("The Rhine Falls", "Rhine Falls"),
    ("The Matterhorn's Gornergrat", "Gornergrat"),
    ("Salzburg's Old Town", "Salzburg"),
    ("The Melk Abbey", "Melk Abbey"),
    ("The Rothenburg ob der Tauber", "Rothenburg ob der Tauber"),
    ("The Black Forest", "Black Forest"),
    ("Sanssouci", "Sanssouci"),
    ("The Bremen Town Musicians", "Bremen Town Musicians"),
    ("Hamburg's Elbphilharmonie", "Elbphilharmonie"),
    ("The Wieliczka Salt Mine", "Wieliczka Salt Mine"),
    ("Auschwitz", "Auschwitz concentration camp"),
    ("The Malbork Castle", "Malbork Castle"),
    ("Bran Castle", "Bran Castle"),
    ("The Painted Monasteries of Bucovina", "Painted churches of northern Moldavia"),
    ("Rila Monastery", "Rila Monastery"),
    ("The Belogradchik Rocks", "Belogradchik Rocks"),
    ("Tallinn's Old Town", "Tallinn Old Town"),
    ("The Curonian Spit", "Curonian Spit"),
    ("Riga's Art Nouveau quarter", "Riga"),
    ("The Northern Lights over Tromsø", "Tromsø"),
    ("The Lofoten Islands", "Lofoten"),
    ("The Atlantic Road", "Atlantic Ocean Road"),
    ("Nærøyfjord", "Nærøyfjord"),
    ("Iceland's Skógafoss", "Skógafoss"),
    ("Iceland's Jökulsárlón", "Jökulsárlón"),
    ("Dettifoss", "Dettifoss"),
    ("The Faroe Islands", "Faroe Islands"),
    ("The Azores", "Azores"),
    ("Madeira", "Madeira"),
    ("The Canary Islands' Teide", "Teide"),
    ("The Rock of Gibraltar", "Rock of Gibraltar"),
    ("Malta's Valletta", "Valletta"),
    ("Mykonos", "Mykonos"),
    ("Rhodes' Old Town", "Medieval City of Rhodes"),
    ("Ephesus", "Ephesus"),
    ("The Hagia Sophia's neighbour, the Basilica Cistern", "Basilica Cistern"),
    ("Mount Ararat", "Mount Ararat"),
    ("The Registan", "Registan"),
    ("The Gur-e-Amir", "Gur-e-Amir"),
    ("The Charminar", "Charminar"),
    ("The Victoria Memorial", "Victoria Memorial, Kolkata"),
    ("Konark Sun Temple", "Konark Sun Temple"),
    ("The Meenakshi Temple", "Meenakshi Temple"),
    ("The Ajanta Caves", "Ajanta Caves"),
    ("The Ellora Caves", "Ellora Caves"),
    ("Mysore Palace", "Mysore Palace"),
    ("The Golden Rock", "Kyaiktiyo Pagoda"),
    ("Bagan", "Bagan"),
    ("The Shwedagon Pagoda", "Shwedagon Pagoda"),
    ("Luang Prabang", "Luang Prabang"),
    ("The Banaue Rice Terraces", "Banaue Rice Terraces"),
    ("Mount Mayon", "Mayon"),
    ("The Chocolate Hills", "Chocolate Hills"),
    ("Komodo National Park", "Komodo National Park"),
    ("Mount Kinabalu", "Mount Kinabalu"),
    ("The Batu Caves", "Batu Caves"),
    ("Angkor Thom", "Angkor Thom"),
    ("The Golden Bridge of Da Nang", "Golden Bridge (Vietnam)"),
    ("The Great Buddha of Kamakura", "Kōtoku-in"),
    ("Mount Koya", "Mount Kōya"),
    ("The Arashiyama bamboo grove", "Arashiyama"),
    ("Osaka Castle", "Osaka Castle"),
    ("Nagoya Castle", "Nagoya Castle"),
    ("The Sapporo Snow Festival", "Sapporo Snow Festival"),
    ("Jeju Island", "Jeju Island"),
    ("The Taipei 101", "Taipei 101"),
    ("The Zhangjiajie pillars", "Zhangjiajie National Forest Park"),
    ("The Potala's neighbour, Jokhang", "Jokhang"),
    ("The Gobi Desert", "Gobi Desert"),
    ("The Trans-Siberian Railway", "Trans-Siberian Railway"),
    ("Lake Baikal", "Lake Baikal"),
    ("The Bolshoi Theatre", "Bolshoi Theatre"),
    ("Kizhi Pogost", "Kizhi Pogost"),
    ("The Wailing Wall's Masada", "Masada"),
    ("Wadi Rum", "Wadi Rum"),
    ("The Jerash ruins", "Jerash"),
    ("Baalbek", "Baalbek"),
    ("The Kaaba", "Kaaba"),
    ("Palmyra", "Palmyra"),
    ("The Cedars of Lebanon", "Cedars of God"),
    ("The Aswan High Dam", "Aswan Dam"),
    ("Luxor Temple", "Luxor Temple"),
    ("The Nile", "Nile"),
    ("The Atlas Mountains", "Atlas Mountains"),
    ("Aït Benhaddou", "Aït Benhaddou"),
    ("The Bahia Palace", "Bahia Palace"),
    ("Timbuktu", "Timbuktu"),
    ("The Zanzibar Stone Town", "Stone Town"),
    ("Mount Kenya", "Mount Kenya"),
    ("The Maasai Mara", "Maasai Mara"),
    ("The Bwindi Forest", "Bwindi Impenetrable National Park"),
    ("The Etosha Pan", "Etosha National Park"),
    ("The Namib Desert", "Namib"),
    ("Sossusvlei", "Sossusvlei"),
    ("The Kruger National Park", "Kruger National Park"),
    ("The Drakensberg", "Drakensberg"),
    ("The Garden Route", "Garden Route"),
    ("The Seychelles", "Seychelles"),
    ("Mauritius", "Mauritius"),
    ("The Aldabra Atoll", "Aldabra"),
    ("The Sydney Tower", "Sydney Tower"),
    ("The Great Ocean Road", "Great Ocean Road"),
    ("Fraser Island", "K'gari"),
    ("The Daintree Rainforest", "Daintree Rainforest"),
    ("Kangaroo Island", "Kangaroo Island"),
    ("The Nullarbor Plain", "Nullarbor Plain"),
    ("Milford Track", "Milford Track"),
    ("Queenstown", "Queenstown, New Zealand"),
    ("The Waitomo Caves", "Waitomo Glowworm Caves"),
    ("Tongariro", "Tongariro National Park"),
    ("The Hobbiton film set", "Hobbiton Movie Set"),
    ("Fiji", "Fiji"),
    ("The Grand Teton", "Grand Teton National Park"),
    ("Yellowstone Falls", "Yellowstone Falls"),
    ("Mount St. Helens", "Mount St. Helens"),
    ("The Columbia River Gorge", "Columbia River Gorge"),
    ("Crater Lake's Wizard Island", "Wizard Island"),
    ("The Big Sur coast", "Big Sur"),
    ("The Bixby Creek Bridge", "Bixby Creek Bridge"),
    ("Joshua Tree", "Joshua Tree National Park"),
    ("The Hoh Rainforest", "Hoh Rainforest"),
    ("The Space Center Houston", "Space Center Houston"),
    ("The Kennedy Space Center", "Kennedy Space Center"),
    ("Savannah's Forsyth Park", "Forsyth Park"),
    ("Charleston's Rainbow Row", "Rainbow Row"),
    ("The Great Smoky Mountains", "Great Smoky Mountains"),
    ("The Mackinac Bridge", "Mackinac Bridge"),
    ("Niagara's Cave of the Winds", "Cave of the Winds (New York)"),
    ("The Adirondacks", "Adirondack Mountains"),
    ("Acadia National Park", "Acadia National Park"),
    ("The Portland Head Light", "Portland Head Light"),
    ("Martha's Vineyard", "Martha's Vineyard"),
    ("The Cape Cod National Seashore", "Cape Cod National Seashore"),
    ("Niagara-on-the-Lake", "Niagara-on-the-Lake"),
    ("Lake Louise's Victoria Glacier", "Victoria Glacier"),
    ("The Icefields Parkway", "Icefields Parkway"),
    ("Whistler", "Whistler, British Columbia"),
    ("Butchart Gardens", "Butchart Gardens"),
    ("The Northern Lights over Yellowknife", "Yellowknife"),
    ("Chichén Itzá's cenotes", "Cenote"),
    ("Copper Canyon", "Copper Canyon"),
    ("Havana's Malecón", "Malecón, Havana"),
    ("The Blue Hole", "Great Blue Hole"),
    ("Monteverde", "Monteverde"),
    ("The Iguazú's Devil's Throat", "Iguazú Falls"),
    ("Buenos Aires' Caminito", "Caminito"),
    ("The Andes", "Andes"),
    ("Cusco", "Cusco"),
    ("The Colca Canyon", "Colca Canyon"),
    ("Valparaíso", "Valparaíso"),
    ("Easter Island's Rano Raraku", "Rano Raraku"),
    ("The Pantanal", "Pantanal"),
    ("Fernando de Noronha", "Fernando de Noronha"),
    ("Ouro Preto", "Ouro Preto"),
    ("The Chapada Diamantina", "Chapada Diamantina National Park"),
]
