"""Animals to add: the title shown, the Wikipedia article, and the class it belongs to.

The class is the point. A Things round asks "which one is a mammal?", and the answer is a
fact about the creature rather than a guess about the picture — which is why this pack can
carry content questions at all where a personal photograph cannot.
"""

ANIMALS = [
    # --- Mammals
    ("A cheetah", "Cheetah", "class-mammal"),
    ("A leopard", "Leopard", "class-mammal"),
    ("A jaguar", "Jaguar", "class-mammal"),
    ("A lynx", "Lynx", "class-mammal"),
    ("A cougar", "Cougar", "class-mammal"),
    ("A snow leopard", "Snow leopard", "class-mammal"),
    ("A brown bear", "Brown bear", "class-mammal"),
    ("A black bear", "American black bear", "class-mammal"),
    ("A grizzly bear", "Grizzly bear", "class-mammal"),
    ("A raccoon", "Raccoon", "class-mammal"),
    ("A badger", "Badger", "class-mammal"),
    ("A skunk", "Skunk", "class-mammal"),
    ("A weasel", "Weasel", "class-mammal"),
    ("A ferret", "Ferret", "class-mammal"),
    ("A beaver", "Beaver", "class-mammal"),
    ("A porcupine", "Porcupine", "class-mammal"),
    ("A squirrel", "Squirrel", "class-mammal"),
    ("A chipmunk", "Chipmunk", "class-mammal"),
    ("A hamster", "Hamster", "class-mammal"),
    ("A guinea pig", "Guinea pig", "class-mammal"),
    ("A rabbit", "Rabbit", "class-mammal"),
    ("A hare", "Hare", "class-mammal"),
    ("A mouse", "Mouse", "class-mammal"),
    ("A rat", "Rat", "class-mammal"),
    ("A mole", "Mole (animal)", "class-mammal"),
    ("A shrew", "Shrew", "class-mammal"),
    ("An armadillo", "Armadillo", "class-mammal"),
    ("An anteater", "Anteater", "class-mammal"),
    ("A pangolin", "Pangolin", "class-mammal"),
    ("An aardvark", "Aardvark", "class-mammal"),
    ("A wombat", "Wombat", "class-mammal"),
    ("A possum", "Opossum", "class-mammal"),
    ("A wallaby", "Wallaby", "class-mammal"),
    ("A Tasmanian devil", "Tasmanian devil", "class-mammal"),
    ("A platypus", "Platypus", "class-mammal"),
    ("An echidna", "Echidna", "class-mammal"),
    ("A lemur", "Lemur", "class-mammal"),
    ("A chimpanzee", "Chimpanzee", "class-mammal"),
    ("An orangutan", "Orangutan", "class-mammal"),
    ("A baboon", "Baboon", "class-mammal"),
    ("A macaque", "Macaque", "class-mammal"),
    ("A marmoset", "Marmoset", "class-mammal"),
    ("A moose", "Moose", "class-mammal"),
    ("An elk", "Elk", "class-mammal"),
    ("A reindeer", "Reindeer", "class-mammal"),
    ("A deer", "Deer", "class-mammal"),
    ("An antelope", "Antelope", "class-mammal"),
    ("A gazelle", "Gazelle", "class-mammal"),
    ("An impala", "Impala", "class-mammal"),
    ("A wildebeest", "Wildebeest", "class-mammal"),
    ("An ibex", "Ibex", "class-mammal"),
    ("A bighorn sheep", "Bighorn sheep", "class-mammal"),
    ("A mountain goat", "Mountain goat", "class-mammal"),
    ("A yak", "Domestic yak", "class-mammal"),
    ("A water buffalo", "Water buffalo", "class-mammal"),
    ("A llama", "Llama", "class-mammal"),
    ("An alpaca", "Alpaca", "class-mammal"),
    ("A donkey", "Donkey", "class-mammal"),
    ("A pony", "Pony", "class-mammal"),
    ("A horse", "Horse", "class-mammal"),
    ("A cow", "Cattle", "class-mammal"),
    ("A sheep", "Sheep", "class-mammal"),
    ("A goat", "Goat", "class-mammal"),
    ("A pig", "Domestic pig", "class-mammal"),
    ("A dog", "Dog", "class-mammal"),
    ("A cat", "Cat", "class-mammal"),
    ("A warthog", "Common warthog", "class-mammal"),
    ("A tapir", "Tapir", "class-mammal"),
    ("A capybara", "Capybara", "class-mammal"),
    ("A manatee", "Manatee", "class-mammal"),
    ("A walrus", "Walrus", "class-mammal"),
    ("A seal", "Pinniped", "class-mammal"),
    ("A sea lion", "Sea lion", "class-mammal"),
    ("A sea otter", "Sea otter", "class-mammal"),
    ("An orca", "Orca", "class-mammal"),
    ("A humpback whale", "Humpback whale", "class-mammal"),
    ("A blue whale", "Blue whale", "class-mammal"),
    ("A narwhal", "Narwhal", "class-mammal"),
    ("A beluga whale", "Beluga whale", "class-mammal"),
    ("A mongoose", "Mongoose", "class-mammal"),
    ("A hyena", "Hyena", "class-mammal"),
    ("A coyote", "Coyote", "class-mammal"),
    ("A dingo", "Dingo", "class-mammal"),
    ("An arctic fox", "Arctic fox", "class-mammal"),
    ("A fennec fox", "Fennec fox", "class-mammal"),
    ("A bushbaby", "Galago", "class-mammal"),
    ("A binturong", "Binturong", "class-mammal"),
    ("A quokka", "Quokka", "class-mammal"),
    ("An okapi", "Okapi", "class-mammal"),

    # --- Birds
    ("A swallow", "Swallow", "class-bird"),
    ("A sparrow", "Sparrow", "class-bird"),
    ("A blackbird", "Common blackbird", "class-bird"),
    ("A blue tit", "Eurasian blue tit", "class-bird"),
    ("A goldfinch", "European goldfinch", "class-bird"),
    ("A chaffinch", "Common chaffinch", "class-bird"),
    ("A wren", "Eurasian wren", "class-bird"),
    ("A starling", "Common starling", "class-bird"),
    ("A magpie", "Eurasian magpie", "class-bird"),
    ("A crow", "Crow", "class-bird"),
    ("A raven", "Common raven", "class-bird"),
    ("A jay", "Eurasian jay", "class-bird"),
    ("A cardinal", "Northern cardinal", "class-bird"),
    ("A blue jay", "Blue jay", "class-bird"),
    ("A hummingbird", "Hummingbird", "class-bird"),
    ("A toucan", "Toucan", "class-bird"),
    ("A macaw", "Macaw", "class-bird"),
    ("A cockatoo", "Cockatoo", "class-bird"),
    ("A budgerigar", "Budgerigar", "class-bird"),
    ("A lovebird", "Lovebird", "class-bird"),
    ("A canary", "Domestic canary", "class-bird"),
    ("A kookaburra", "Kookaburra", "class-bird"),
    ("A kiwi", "Kiwi (bird)", "class-bird"),
    ("An emu", "Emu", "class-bird"),
    ("A cassowary", "Cassowary", "class-bird"),
    ("A heron", "Heron", "class-bird"),
    ("A stork", "Stork", "class-bird"),
    ("A crane", "Crane (bird)", "class-bird"),
    ("An ibis", "Ibis", "class-bird"),
    ("A spoonbill", "Spoonbill", "class-bird"),
    ("An egret", "Egret", "class-bird"),
    ("A seagull", "Gull", "class-bird"),
    ("An albatross", "Albatross", "class-bird"),
    ("A cormorant", "Cormorant", "class-bird"),
    ("A gannet", "Gannet", "class-bird"),
    ("A tern", "Tern", "class-bird"),
    ("A goose", "Goose", "class-bird"),
    ("A mallard", "Mallard", "class-bird"),
    ("A pheasant", "Common pheasant", "class-bird"),
    ("A partridge", "Partridge", "class-bird"),
    ("A quail", "Quail", "class-bird"),
    ("A turkey", "Turkey (bird)", "class-bird"),
    ("A chicken", "Chicken", "class-bird"),
    ("A rooster", "Rooster", "class-bird"),
    ("A hawk", "Hawk", "class-bird"),
    ("A falcon", "Falcon", "class-bird"),
    ("A kestrel", "Common kestrel", "class-bird"),
    ("A golden eagle", "Golden eagle", "class-bird"),
    ("A vulture", "Vulture", "class-bird"),
    ("A condor", "Andean condor", "class-bird"),
    ("A barn owl", "Barn owl", "class-bird"),
    ("A snowy owl", "Snowy owl", "class-bird"),
    ("A nightingale", "Common nightingale", "class-bird"),
    ("A cuckoo", "Common cuckoo", "class-bird"),
    ("A hoopoe", "Hoopoe", "class-bird"),
    ("A hornbill", "Hornbill", "class-bird"),
    ("A bird of paradise", "Bird-of-paradise", "class-bird"),
    ("A roadrunner", "Roadrunner", "class-bird"),
    ("A puffin's cousin, the razorbill", "Razorbill", "class-bird"),

    # --- Reptiles
    ("An alligator", "Alligator", "class-reptile"),
    ("A caiman", "Caiman", "class-reptile"),
    ("A rattlesnake", "Rattlesnake", "class-reptile"),
    ("A boa constrictor", "Boa constrictor", "class-reptile"),
    ("An anaconda", "Green anaconda", "class-reptile"),
    ("A viper", "Viperidae", "class-reptile"),
    ("A grass snake", "Grass snake", "class-reptile"),
    ("A sea turtle", "Sea turtle", "class-reptile"),
    ("A box turtle", "Box turtle", "class-reptile"),
    ("A Galápagos tortoise", "Galápagos tortoise", "class-reptile"),
    ("A monitor lizard", "Monitor lizard", "class-reptile"),
    ("A skink", "Skink", "class-reptile"),
    ("A bearded dragon", "Central bearded dragon", "class-reptile"),
    ("A horned lizard", "Horned lizard", "class-reptile"),
    ("A frilled lizard", "Frilled-neck lizard", "class-reptile"),
    ("A marine iguana", "Marine iguana", "class-reptile"),
    ("A tuatara", "Tuatara", "class-reptile"),

    # --- Amphibians
    ("A toad", "Toad", "class-amphibian"),
    ("A bullfrog", "American bullfrog", "class-amphibian"),
    ("A poison dart frog", "Poison dart frog", "class-amphibian"),
    ("A newt", "Newt", "class-amphibian"),
    ("A fire salamander", "Fire salamander", "class-amphibian"),
    ("A caecilian", "Caecilian", "class-amphibian"),
    ("A glass frog", "Glass frog", "class-amphibian"),

    # --- Fish
    ("A trout", "Trout", "class-fish"),
    ("A carp", "Carp", "class-fish"),
    ("A koi", "Koi", "class-fish"),
    ("A catfish", "Catfish", "class-fish"),
    ("A pike", "Northern pike", "class-fish"),
    ("A bass", "Bass (fish)", "class-fish"),
    ("A tuna", "Tuna", "class-fish"),
    ("A herring", "Herring", "class-fish"),
    ("A mackerel", "Mackerel", "class-fish"),
    ("A cod", "Atlantic cod", "class-fish"),
    ("An eel", "Eel", "class-fish"),
    ("A manta ray", "Manta ray", "class-fish"),
    ("A hammerhead shark", "Hammerhead shark", "class-fish"),
    ("A whale shark", "Whale shark", "class-fish"),
    ("An angelfish", "Marine angelfish", "class-fish"),
    ("A pufferfish", "Tetraodontidae", "class-fish"),
    ("A lionfish", "Pterois", "class-fish"),
    ("A barracuda", "Barracuda", "class-fish"),
    ("A piranha", "Piranha", "class-fish"),
    ("A sturgeon", "Sturgeon", "class-fish"),
    ("A flying fish", "Flying fish", "class-fish"),
    ("A sunfish", "Ocean sunfish", "class-fish"),

    # --- Insects
    ("A beetle", "Beetle", "class-insect"),
    ("A stag beetle", "Stag beetle", "class-insect"),
    ("A dung beetle", "Dung beetle", "class-insect"),
    ("A weevil", "Weevil", "class-insect"),
    ("A praying mantis", "Mantis", "class-insect"),
    ("A stick insect", "Phasmatodea", "class-insect"),
    ("A cicada", "Cicada", "class-insect"),
    ("A locust", "Locust", "class-insect"),
    ("A termite", "Termite", "class-insect"),
    ("A hornet", "Hornet", "class-insect"),
    ("A bumblebee", "Bumblebee", "class-insect"),
    ("A hoverfly", "Hoverfly", "class-insect"),
    ("A housefly", "Housefly", "class-insect"),
    ("A mosquito", "Mosquito", "class-insect"),
    ("A caterpillar", "Caterpillar", "class-insect"),
    ("A monarch butterfly", "Monarch butterfly", "class-insect"),
    ("A swallowtail butterfly", "Swallowtail butterfly", "class-insect"),
    ("A luna moth", "Luna moth", "class-insect"),
    ("An earwig", "Earwig", "class-insect"),
    ("A water strider", "Gerridae", "class-insect"),
]

# --- Second batch.
ANIMALS += [
    ("A serval", "Serval", "class-mammal"),
    ("A caracal", "Caracal", "class-mammal"),
    ("An ocelot", "Ocelot", "class-mammal"),
    ("A sand cat", "Sand cat", "class-mammal"),
    ("A sun bear", "Sun bear", "class-mammal"),
    ("A sloth bear", "Sloth bear", "class-mammal"),
    ("A spectacled bear", "Spectacled bear", "class-mammal"),
    ("A wolverine", "Wolverine", "class-mammal"),
    ("A stoat", "Stoat", "class-mammal"),
    ("A pine marten", "Pine marten", "class-mammal"),
    ("A civet", "Viverridae", "class-mammal"),
    ("A genet", "Genet (animal)", "class-mammal"),
    ("A coati", "Coati", "class-mammal"),
    ("A kinkajou", "Kinkajou", "class-mammal"),
    ("A red squirrel", "Red squirrel", "class-mammal"),
    ("A flying squirrel", "Flying squirrel", "class-mammal"),
    ("A prairie dog", "Prairie dog", "class-mammal"),
    ("A marmot", "Marmot", "class-mammal"),
    ("A groundhog", "Groundhog", "class-mammal"),
    ("A gerbil", "Gerbil", "class-mammal"),
    ("A chinchilla", "Chinchilla", "class-mammal"),
    ("A lemming", "Lemming", "class-mammal"),
    ("A vole", "Vole", "class-mammal"),
    ("A pika", "Pika", "class-mammal"),
    ("A jackrabbit", "Jackrabbit", "class-mammal"),
    ("A gibbon", "Gibbon", "class-mammal"),
    ("A mandrill", "Mandrill", "class-mammal"),
    ("A howler monkey", "Howler monkey", "class-mammal"),
    ("A spider monkey", "Spider monkey", "class-mammal"),
    ("A squirrel monkey", "Squirrel monkey", "class-mammal"),
    ("A tarsier", "Tarsier", "class-mammal"),
    ("A ring-tailed lemur", "Ring-tailed lemur", "class-mammal"),
    ("An aye-aye", "Aye-aye", "class-mammal"),
    ("A caribou", "Reindeer", "class-mammal"),
    ("A roe deer", "Roe deer", "class-mammal"),
    ("A fallow deer", "Fallow deer", "class-mammal"),
    ("A pronghorn", "Pronghorn", "class-mammal"),
    ("An oryx", "Oryx", "class-mammal"),
    ("A kudu", "Kudu", "class-mammal"),
    ("A springbok", "Springbok", "class-mammal"),
    ("A chamois", "Chamois", "class-mammal"),
    ("A musk ox", "Muskox", "class-mammal"),
    ("An addax", "Addax", "class-mammal"),
    ("A bongo", "Bongo (antelope)", "class-mammal"),
    ("A dik-dik", "Dik-dik", "class-mammal"),
    ("A vicuña", "Vicuña", "class-mammal"),
    ("A guanaco", "Guanaco", "class-mammal"),
    ("A Bactrian camel", "Bactrian camel", "class-mammal"),
    ("A donkey's cousin, the onager", "Onager", "class-mammal"),
    ("A Przewalski's horse", "Przewalski's horse", "class-mammal"),
    ("A Shetland pony", "Shetland pony", "class-mammal"),
    ("A Highland cow", "Highland cattle", "class-mammal"),
    ("A dugong", "Dugong", "class-mammal"),
    ("A harbour porpoise", "Harbour porpoise", "class-mammal"),
    ("A sperm whale", "Sperm whale", "class-mammal"),
    ("A right whale", "Right whale", "class-mammal"),
    ("A grey seal", "Grey seal", "class-mammal"),
    ("An elephant seal", "Elephant seal", "class-mammal"),
    ("A leopard seal", "Leopard seal", "class-mammal"),
    ("A giant otter", "Giant otter", "class-mammal"),
    ("A honey badger", "Honey badger", "class-mammal"),
    ("A meerkat's cousin, the suricate's kin the banded mongoose", "Banded mongoose", "class-mammal"),
    ("An African wild dog", "African wild dog", "class-mammal"),
    ("A maned wolf", "Maned wolf", "class-mammal"),
    ("A red wolf", "Red wolf", "class-mammal"),
    ("A jackal", "Jackal", "class-mammal"),
    ("A bush baby's kin, the potto", "Potto", "class-mammal"),
    ("A numbat", "Numbat", "class-mammal"),
    ("A bilby", "Bilby", "class-mammal"),
    ("A sugar glider", "Sugar glider", "class-mammal"),
    ("A tree kangaroo", "Tree-kangaroo", "class-mammal"),

    ("A bee-eater", "Bee-eater", "class-bird"),
    ("A kingfisher's cousin, the roller", "Roller (bird)", "class-bird"),
    ("A lapwing", "Northern lapwing", "class-bird"),
    ("A curlew", "Curlew", "class-bird"),
    ("An oystercatcher", "Oystercatcher", "class-bird"),
    ("A sandpiper", "Sandpiper", "class-bird"),
    ("A plover", "Plover", "class-bird"),
    ("A skua", "Skua", "class-bird"),
    ("A petrel", "Petrel", "class-bird"),
    ("A shearwater", "Shearwater", "class-bird"),
    ("A frigatebird", "Frigatebird", "class-bird"),
    ("A booby", "Booby", "class-bird"),
    ("A grebe", "Grebe", "class-bird"),
    ("A coot", "Coot", "class-bird"),
    ("A moorhen", "Moorhen", "class-bird"),
    ("A teal", "Eurasian teal", "class-bird"),
    ("A widgeon", "Eurasian wigeon", "class-bird"),
    ("An eider", "Common eider", "class-bird"),
    ("A merganser", "Merganser", "class-bird"),
    ("A grouse", "Grouse", "class-bird"),
    ("A ptarmigan", "Rock ptarmigan", "class-bird"),
    ("A capercaillie", "Western capercaillie", "class-bird"),
    ("A guinea fowl", "Guineafowl", "class-bird"),
    ("A peahen", "Peafowl", "class-bird"),
    ("A parakeet", "Parakeet", "class-bird"),
    ("A lorikeet", "Lorikeet", "class-bird"),
    ("A cockatiel", "Cockatiel", "class-bird"),
    ("A kea", "Kea", "class-bird"),
    ("A woodlark", "Woodlark", "class-bird"),
    ("A skylark", "Eurasian skylark", "class-bird"),
    ("A thrush", "Thrush (bird)", "class-bird"),
    ("A robin's American cousin", "American robin", "class-bird"),
    ("A bluebird", "Bluebird", "class-bird"),
    ("A warbler", "Warbler", "class-bird"),
    ("A finch", "Finch", "class-bird"),
    ("A bullfinch", "Eurasian bullfinch", "class-bird"),
    ("A siskin", "Eurasian siskin", "class-bird"),
    ("A waxwing", "Waxwing", "class-bird"),
    ("A nuthatch", "Nuthatch", "class-bird"),
    ("A treecreeper", "Treecreeper", "class-bird"),
    ("A dipper", "Dipper", "class-bird"),
    ("A swift", "Common swift", "class-bird"),
    ("A nightjar", "European nightjar", "class-bird"),
    ("A pelican's cousin, the shoebill", "Shoebill", "class-bird"),
    ("A secretary bird", "Secretarybird", "class-bird"),
    ("An osprey", "Osprey", "class-bird"),
    ("A harrier", "Harrier (bird)", "class-bird"),
    ("A buzzard", "Common buzzard", "class-bird"),
    ("A sea eagle", "White-tailed eagle", "class-bird"),
    ("A little owl", "Little owl", "class-bird"),
    ("A tawny owl", "Tawny owl", "class-bird"),
    ("A quetzal", "Resplendent quetzal", "class-bird"),
    ("A puffbird", "Puffbird", "class-bird"),
    ("A motmot", "Motmot", "class-bird"),
    ("A weaver bird", "Ploceidae", "class-bird"),
    ("An oxpecker", "Oxpecker", "class-bird"),
    ("A hoatzin", "Hoatzin", "class-bird"),
    ("A rhea", "Rhea (bird)", "class-bird"),
    ("A crested crane", "Grey crowned crane", "class-bird"),

    ("A gharial", "Gharial", "class-reptile"),
    ("A saltwater crocodile", "Saltwater crocodile", "class-reptile"),
    ("A king cobra", "King cobra", "class-reptile"),
    ("A coral snake", "Coral snake", "class-reptile"),
    ("A milk snake", "Milk snake", "class-reptile"),
    ("A python's cousin, the reticulated python", "Reticulated python", "class-reptile"),
    ("A garter snake", "Garter snake", "class-reptile"),
    ("A leatherback turtle", "Leatherback sea turtle", "class-reptile"),
    ("A loggerhead turtle", "Loggerhead sea turtle", "class-reptile"),
    ("A snapping turtle", "Common snapping turtle", "class-reptile"),
    ("A terrapin", "Terrapin", "class-reptile"),
    ("A basilisk lizard", "Basilisk lizard", "class-reptile"),
    ("A Gila monster", "Gila monster", "class-reptile"),
    ("A thorny devil", "Thorny devil", "class-reptile"),
    ("A slow worm", "Slow worm", "class-reptile"),

    ("A tree frog's cousin, the red-eyed tree frog", "Agalychnis callidryas", "class-amphibian"),
    ("A common frog", "Common frog", "class-amphibian"),
    ("A natterjack toad", "Natterjack toad", "class-amphibian"),
    ("A hellbender", "Hellbender", "class-amphibian"),
    ("A mudpuppy", "Mudpuppy", "class-amphibian"),
    ("An olm", "Olm", "class-amphibian"),
    ("A tadpole", "Tadpole", "class-amphibian"),

    ("A halibut", "Halibut", "class-fish"),
    ("A plaice", "European plaice", "class-fish"),
    ("A sole", "Common sole", "class-fish"),
    ("A sardine", "Sardine", "class-fish"),
    ("An anchovy", "Anchovy", "class-fish"),
    ("A swordfish's cousin, the marlin", "Marlin", "class-fish"),
    ("A sailfish", "Sailfish", "class-fish"),
    ("A grouper", "Grouper", "class-fish"),
    ("A snapper", "Lutjanidae", "class-fish"),
    ("A parrotfish", "Parrotfish", "class-fish"),
    ("A wrasse", "Wrasse", "class-fish"),
    ("A moray eel", "Moray eel", "class-fish"),
    ("A guppy", "Guppy", "class-fish"),
    ("A betta", "Siamese fighting fish", "class-fish"),
    ("A sawfish", "Sawfish", "class-fish"),
    ("An electric eel", "Electric eel", "class-fish"),
    ("A coelacanth", "Coelacanth", "class-fish"),
    ("A seadragon", "Leafy seadragon", "class-fish"),

    ("A ground beetle", "Ground beetle", "class-insect"),
    ("A click beetle", "Click beetle", "class-insect"),
    ("A june bug", "June beetle", "class-insect"),
    ("A leaf insect", "Phylliidae", "class-insect"),
    ("A katydid", "Tettigoniidae", "class-insect"),
    ("A mayfly", "Mayfly", "class-insect"),
    ("A damselfly", "Damselfly", "class-insect"),
    ("A lacewing", "Neuroptera", "class-insect"),
    ("A shield bug", "Pentatomidae", "class-insect"),
    ("An aphid", "Aphid", "class-insect"),
    ("A carpenter bee", "Carpenter bee", "class-insect"),
    ("A paper wasp", "Paper wasp", "class-insect"),
    ("A leafcutter ant", "Leafcutter ant", "class-insect"),
    ("A weaver ant", "Weaver ant", "class-insect"),
    ("A flea", "Flea", "class-insect"),
    ("A silverfish", "Silverfish", "class-insect"),
    ("A hawk moth", "Sphingidae", "class-insect"),
    ("A peacock butterfly", "Aglais io", "class-insect"),
    ("A red admiral", "Red admiral", "class-insect"),
    ("A painted lady", "Vanessa cardui", "class-insect"),
]
